# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SI676 Test Site (but I figured it out this time)
email: asaakov@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  Figuring Jekyll out for Github pages was confusing. There are
  a lot of layers to it, like cake or many other food-related
  items.
domain: artemsaakov.github.io
url: https://artemsaakov.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /test-site-jekyll # the subpath of your site, e.g. /blog
github_username:  ArtemSaakov

# Build settings
markdown: kramdown
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .devcontainer/
